### PR TITLE
Bug fixes and add proto instance

### PR DESCRIPTION
**Pull request by leopoldodonnell**
I've fixed
- a typo
- a change in naming for policy options

I've add a new task that gets run after setup. This task adds the instance referred to by :app to the newly created load balancer.

### CODE REVIEW

**Comment by yyuu** [comment]
Thanks for sending patch :+1:

I can merge these changes without any problems because they're just fixing existing features.
- cc943f2eec0a28003a31f2cdfd28d6344e33f691
- dfd2f4b728cef482309127a1ce5cae4945631635

Though, 52f184f42f36fc59d1a600268ed36a0928d8b42d is a new feature. I need more investigation for merging this. Please create another issue for 52f184f42f36fc59d1a600268ed36a0928d8b42d.

**Comment by leopoldodonnell** [comment]
I'll put another pull request together after I get my release pushed today.

Thanks for putting these recipes together, it saved me a ton of time switching away from elastic beanstalk.

Cheers,

Leo O'Donnell 
617.871.9412

**Comment by yyuu** [comment]
Sorry, I've forgotten to merge this.... I'll create a new gem release 0.0.8 soon.

**Comment by yyuu** [comment]
I am so sorry for the delay. I released v0.0.8 on rubygems.org. It will be available soon.

**Pull request merged**
